# -*- coding: utf-8 -*-
"""Copy of AliceBlue Sample Program #1 - Connecting to Websocket and Getting Live LTP - By Unofficed

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_8kqUqRZuIpBU3efXaMAL1CIqoEfa2RW
"""

#Google Collab Link - https://colab.research.google.com/drive/1vJmIXGTPe8Ckkx_psmO2Z5h4FXbp1Z4H?usp=sharing
#Install The Python Wrapper

#!pip install alice_blue

#Importing AliceBlue Library
from alice_blue import *

#Only Replace it with your credentails
#Follow https://unofficed.com/how-to-activate-the-api-in-alice-blue-for-automated-trading/ for generating api_ID and api_Secret 

#Only Replace it with your credentails
username    = "AB067538" 
password    = "SpiritFav66*" 
twoFA       = "243396"
app_id      = "UDXXPjmSSFeqeac"
#api_secret  = "eYyYHWcDyOtLOxCOZcsTTfUujvEcuhgNJgryaQcufVaGXmIKsygsmiABDDGsBIbqHGaQQdFtYNLTSPcESmeTNLTJxbQGNikyFUDi"
api_secret = 'A2oYu9unGxQeLyazBgNHz3rMsvEi2Bnvx2T0PCGJW60QNmf8HvuLtuzQdJzH9JxJmeLbHkkiNOBIdSmUOgSeRV0riIhZ9b61kDuf66tko7RFLNsvAdfyORAN382UzINg'

#Generating Session ID
session_id = AliceBlue.login_and_get_sessionID(username=username,password=password,twoFA=twoFA,app_id=app_id,api_secret=api_secret)

#Generate an Alice object using the session_id
alice = AliceBlue(username = username, session_id = session_id, master_contracts_to_download=['NSE', 'BSE','NFO','MCX'])

print(alice.get_balance()) # get balance / margin limits

print(alice.get_scrip_info(alice.get_instrument_by_symbol("NSE", "INFY-EQ")))

print(alice.get_scrip_info(alice.get_instrument_by_symbol("NFO", "BANKNIFTY23MARFUT")))

#Getting Instrument of Crude Oil
crude_oil_symbol = alice.get_instrument_by_symbol('MCX', 'CRUDEOIL23MARFUT')
crude_oil_symbol

#Starting the Websocket and Subscribing to a Scrip
tick = 0
def event_handler_quote_update(message):
    global tick
    tick=message

alice.start_websocket(subscribe_callback=event_handler_quote_update)

#This subscribe function takes the first variable type as Instrument. We had this from last block. Second variable is selection between Tick Data or Depth Data.
alice.subscribe(crude_oil_symbol, LiveFeedType.TICK_DATA)

alice.get_all_subscriptions()

#Websocket is connected. Now Lets get the LTP
from time import sleep
while True:
  try:  
    print(tick['instrument'][2]+" : "+str(tick['ltp']))
  except TypeError: #Tick data comes when there is no trade. We are checking for tick data each 5 seconds. If there is no trade in between those 5 seconds, it will reply 0. That will raise an error. We are ignoring it.
    pass
  sleep(5)

